### ISSUE TITLE
Making it possible to use useDeepFreeze() and other plugins as angular's enviroment variable

### ISSUE THREAD

**Issue by st-clair-clarke** [zuriscript/signalstory#14]
I note the advice given relating to useDeepFreeze() at [https://zuriscript.github.io/signalstory/docs/plugins/deep-freeze](https://zuriscript.github.io/signalstory/docs/plugins/deep-freeze). You also suggest that useDeepFreeze() would be recommended for the development cycle because of the overhead hit possible.

Given your advice, how could we set the plugins outside of store initialization? This would allow for me to use angular environment variables to set the plugins usage.

For example, I would be able to do something like the following:

```
if (!environment.production) {
   useDeepFreeze()
}


```

This would allow me to set and forget the plugins usage. In its current implementation, I will have to remember to remove the useDeepFreeze() for production.

Do let me know what you think.

Cheers.

**Comment by zuriscript** [comment]
This can't be part of the library and should be done by the client himself.
You have multiple options with different semantics, let's look a those two:

**Option 1: Instantiate the plugins directly in the constructor**
```typescript
// file: environment.ts
export const environment = {
  isProd: true,
};

// file: environment.development.ts
export const environment = {
  isProd: false,
};

// file: user-store.ts
@Injectable({ providedIn: 'root' })
class UserStore extends ImmutableStore<User[]> {
  constructor() {
    super({
      initialState: [],
      enableLogging: !environment.isProd,
      plugins: [
        ...(environment.isProd ? [] : [useDeepFreeze(), useDevtools()]),
      ],
    });
  }
}
```

The shortcoming of Option 1, is, that the `useDeepFreeze` and `useDevtools` most probably won't be tree shaken and hence will also be part of the production bundle, though this could be acceptable.

**Option 2: Instantiate the plugins lazily inside the environment configuration**
```typescript
// file: environment.ts
export const environment = {
  isProd: true,
  defaultStorePlugins: () => [],
};

// file: environment.development.ts
export const environment = {
  isProd: false,
  defaultStorePlugins: () => [useDevtools(), useDeepFreeze()],
};

// file: user-store.ts
@Injectable({ providedIn: 'root' })
class UserStore extends ImmutableStore<User[]> {
  constructor() {
    super({
      initialState: [],
      enableLogging: !environment.isProd,
      plugins: [
        ...environment.defaultStorePlugins(),
      ],
    });
  }
}
```

Using option 2 and due to file replacement, there will be no trace of `useDeepFreeze` and `useDevtools` in the productive build.

@st-clair-clarke Does this work for you?

**Comment by st-clair-clarke** [comment]
I tried option 2, and it does not work for me - ReduxDevTool now does not display anything.

**Comment by zuriscript** [comment]
It should work.

Please, check those things first; otherwise paste the relevant code here, so I can give you further assistence
- Make sure you're using the right environment file, resp. using the matching build configuration and file replacement build task is correctly configured in angular.json
- Make sure you're actually applying the plugin factory function: <pre>() => [useDevtools<b>()</b>, useDeepFreeze<b>()</b>]</pre>
- Make sure you're calling the environment property correctly and also spreading the result
<pre><b>...</b>environment.defaultStorePlugins<b>()</b></pre>
- It could also be a redux devtools issue:
   - Could you try another browser
   - Keep redux devtools console open on firt hot Reload refresh

**Comment by st-clair-clarke** [comment]
Maybe the reason why its not working for me could be:
1. I am using MIcrofrontends with Dynamic Module Federation (Nx): [Advanced Angular Micro Frontends with Dynamic Module Federation](https://nx.dev/recipes/angular/dynamic-module-federation-with-angular#advanced-angular-micro-frontends-with-dynamic-module-federation)
2. Here mesoft and registration are both application developed using Domain Driven Designs.
3. Each app will have its own project.json (angular.json replacement in nx).
4. I will continue to try it and update you.

The current error it shows is 


```
ERROR Error: Uncaught (in promise): Error: Attempted to call addToHistory on RegistrationStore but history is disabled for this store
Error: Attempted to call addToHistory on RegistrationStore but history is disabled for this store
    at addToHistory (signalstory.mjs:632:15)
    at preprocessCommand (signalstory.mjs:681:13)
    at signalstory.mjs:183:47
    at Array.forEach (<anonymous>)
    at RegistrationStore.set (signalstory.mjs:183:34)
    at init (signalstory.mjs:786:23)
    at signalstory.mjs:163:45
    at Array.forEach (<anonymous>)
    at new Store (signalstory.mjs:163:32)
    at new ImmutableStore (signalstory.mjs:327:9)
    at resolvePromise (zone.js:1193:31)
    at resolvePromise (zone.js:1147:17)
    at zone.js:1260:17
    at _ZoneDelegate.invokeTask (zone.js:402:31)
    at core.mjs:27127:55
    at AsyncStackTaggingZoneSpec.onInvokeTask (core.mjs:27127:36)
    at _ZoneDelegate.invokeTask (zone.js:401:60)
    at Object.onInvokeTask (core.mjs:27437:33)
    at _ZoneDelegate.invokeTask (zone.js:401:60)
    at Zone.runTask (zone.js:173:47)
handleError @ core.mjs:10920
next @ core.mjs:28056
next @ Subscriber.js:91
_next @ Subscriber.js:60
next @ Subscriber.js:31
(anonymous) @ Subject.js:34
errorContext @ errorContext.js:19
next @ Subject.js:27
emit @ core.mjs:23216
(anonymous) @ core.mjs:27476
invoke @ zone.js:368
run @ zone.js:129
runOutsideAngular @ core.mjs:27349
onHandleError @ core.mjs:27476
handleError @ zone.js:372
runGuarded @ zone.js:142
api.microtaskDrainDone @ zone.js:1054
drainMicroTaskQueue @ zone.js:588
Promise.then (async)
nativeScheduleMicroTask @ zone.js:557
scheduleMicroTask @ zone.js:568
scheduleTask @ zone.js:392
onScheduleTask @ core.mjs:27122
scheduleTask @ zone.js:382
onScheduleTask @ zone.js:279
scheduleTask @ zone.js:382
scheduleTask @ zone.js:216
scheduleMicroTask @ zone.js:236
scheduleResolveOrReject @ zone.js:1247
resolvePromise @ zone.js:1184
(anonymous) @ zone.js:1100
(anonymous) @ zone.js:1116
webpackJsonpCallback @ jsonp chunk loading:77
(anonymous) @ node_modules_pnpm_date-fns_2_30_0_node_modules_date-fns_esm_index_js.js:1
Show 32 more frames
Show less

```

**Comment by zuriscript** [comment]
The error that you have pasted, is about the history plugin.
The plugin intercepts each command to the store and preserves the state in the history.

However, Looking at your stacktrace, I think, I have spot the issue.
I assume you are using both the **StorePersistencePlugin** and the **HistoryPlugin**?
And looking at the stacktrace, I further assume, that you have used following registration order: `useStorePersistence(), [...], useStoreHistory()`?

The issue is the following: StorePersistencePlugin attempts to create a new state while also writing to the history, bevore it has actually been registered by the storeHistoryPlugin.

**Temporary Workaround:**
Make sure, that you register `useStoreHistory` first and then register `useStorePersistence`.

**Longterm solution:**
We're using `signalstory` in industrial projects, but haven't used many plugins at the same time, yet.
Middleware ordering can be quite a hard problem.
I will fix it in the upcoming release and will make sure that there is a functioning precedence for built-in plugins


If you still have issues with redux devtools, I would love to hear more.

**Comment by st-clair-clarke** [comment]
Great! You were spot on with the diagnosis. Everything is fine now.
