### ISSUE TITLE
structurajs cannot parse Date type

### ISSUE THREAD

**Issue by st-clair-clarke** [zuriscript/signalstory#9]
Please see [https://github.com/giusepperaso/structura.js/issues/108](https://github.com/giusepperaso/structura.js/issues/108)

**Comment by zuriscript** [comment]
Thanks for using my library.
I'm actually using `immer.js` in conjunction with signalstory, and I didn't had the time to try out `structura.js` directly.
The error is due to type inference issues, I have provided a solution at [your linked issue](https://github.com/giusepperaso/structura.js/issues/108).

Simplest workaround:
```typescript
export type MutationFn<T> = (currentState: T, mutation: (draftState: T) => void) => T;
// [...]
cloneAndMutateFunc: produce as unknown as MutationFn<TAge>
```

**Comment by st-clair-clarke** [comment]
Works nicely. Thanks.

**Comment by zuriscript** [comment]
I have added a section about structura.js in the docs in #11
